import type { AppData, DateKey } from './types'
import type { Anchor } from './schedule'
import { prayerTimes } from './prayer'
import { routineAnchors } from './routines'

/**
 * Every fixed commitment on a day — prayers and routines — as plain anchors.
 *
 * This is the one place the two are merged. The same six-line prayer expression
 * used to be written out separately in `SchedulePane.generate()` and
 * `DataContext.replan()`, which meant routines would have had to be added to
 * both, and a day generated by the button could disagree with the same day seen
 * by the planner.
 *
 * Resolution stays out of `schedule.ts` and `plan.ts` on purpose: both take
 * anchors as data and neither knows what a prayer or a routine is.
 */
export function dayAnchors(data: AppData, date: DateKey): Anchor[] {
  const prayers: Anchor[] = data.prayer.enabled
    ? prayerTimes(date, data.prayer)
        .filter((t) => data.prayer.include.includes(t.name))
        .map((t) => ({
          name: t.name,
          start: t.minutes,
          end: t.minutes + data.prayer.blockMinutes,
          source: 'prayer' as const
        }))
    : []

  return [...prayers, ...routineAnchors(data.routines, date)].sort((a, b) => a.start - b.start)
}
